apiVersion: v1
kind: Service
metadata:
  name: sra-discoveryservice
spec:
  selector:
    app: sra-discoveryservice
  ports:
    - port: 80
      targetPort: 8761
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sra-discoveryservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sra-discoveryservice
  template:
    metadata:
      labels:
        app: sra-discoveryservice
    spec:
      containers:
        - name: app
          image: nisanthan/sra-discoveryservice
          ports:
            - containerPort: 8761
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sra-course
spec:
  selector:
    app: sra-course
  ports:
    - port: 80
      targetPort: 8001
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sra-course
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sra-course
  template:
    metadata:
      labels:
        app: sra-course
    spec:
      containers:
        - name: app
          image: nisanthan/sra-course
          ports:
            - containerPort: 8001
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sra-student
spec:
  selector:
    app: sra-student
  ports:
    - port: 80
      targetPort: 8002
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sra-student
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sra-student
  template:
    metadata:
      labels:
        app: sra-student
    spec:
      containers:
        - name: app
          image: nisanthan/sra-student
          ports:
            - containerPort: 8002
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sra-coursecatelog
spec:
  selector:
    app: sra-coursecatelog
  ports:
    - port: 80
      targetPort: 8000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sra-coursecatelog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sra-coursecatelog
  template:
    metadata:
      labels:
        app: sra-coursecatelog
    spec:
      containers:
        - name: app
          image: nisanthan/sra-coursecatelog
          ports:
            - containerPort: 8000
          imagePullPolicy: Always